"""Remove extra column

Revision ID: f5f0eb54b53c
Revises: c6fb646dc91e
Create Date: 2024-02-15 08:20:12.440142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f0eb54b53c'
down_revision: Union[str, None] = 'c6fb646dc91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
